# Data Cleaning — Amazon Fitness Clothing Dataset

## Objective
Clean and transform the raw scraped Amazon dataset into a 
structured, analysis-ready format.

## Cleaning Steps Performed
1. Extracted currency (PKR/$) into a separate `Currency` column
2. Removed currency symbols and converted prices to numeric (float)
3. Cleaned `Total Reviews` by removing parentheses and commas
4. Converted `Delivery Charges` to numeric values
5. Calculated `Discount Amount` and `Discount Percent` from 
   current vs typical price
6. Standardized column names for consistency

## Key Observations
- Dataset reduced from 385 to 224 rows after removing 
  rows with missing or unparseable price data
- Some products had misaligned fabric/care/origin fields 
  due to inconsistent HTML structure across Amazon listings
- Most products are priced in PKR (Pakistani Rupees)

## Output
A clean 224-row, 13-column CSV: `5-amazon_products.csv`
Ready for exploratory data analysis and visualization.

## Importing Libraries

In [18]:
import pandas as pd
import numpy as np

## Reading Data From Scraped DataSet

In [19]:
ds = pd.read_csv('4-amazon_products.csv')
ds

,Product Name,Current Price,Typical Price,Rating,Total Reviews,Delivery Charges,Fabric Type,Care Instructions,Origin,Customer Reviews
0,MAGCOMSEN Men's Short Sleeve Moisture Wicking ...,"PKR 2,782.71 with 60 percent savings","PKR6,958.18",4.1 out of 5 stars,(49),"PKR 17,796.56 Shipping & Import Charges to Pak...",100% Polyester,Imported,Pull On,"{'Hubby loves them!': '5 out of 5 stars', 'Per..."
1,Kewlioo Men's Heat Trapping Zipper Sweat Enhan...,"PKR 6,682.41",NaN,4.2 out of 5 stars,"(6,804)","PKR 17,896.84 Shipping & Import Charges to Pak...","Outer: 90% Polyester, 10% Spandex. Inner: 100%...",Machine Wash,Imported,"{'Passt die Größe': '3 out of 5 stars', 'Gym':..."
2,HOTSUIT Sauna Suit for Men Sweat Sauna Jacket ...,"PKR 11,417.76",NaN,4.6 out of 5 stars,"(9,967)","PKR 21,008.24 Shipping & Import Charges to Pak...",Polyester,Hand Wash Only,Imported,"{'Super zum Abnehmen': '5 out of 5 stars', 'Bo..."
3,INTO THE AM Mens T Shirts Soft Cotton Blend Cr...,"PKR 3,328.67",NaN,4.4 out of 5 stars,"(31,438)","PKR 20,387.07 Shipping & Import Charges to Pak...","60% Cotton, 40% Polyester",Machine Wash,Made in the USA or Imported,"{'Good': '5 out of 5 stars', 'Valor Precio': '..."
4,Kinglaman 1/5 Pack Mesh Workout Shirts for Men...,"PKR 6,682.41",NaN,4.6 out of 5 stars,"(2,810)","PKR 24,442.76 Shipping & Import Charges to Pak...",1OO% Polyester,Machine Wash,Imported,"{'Value for money!': '5 out of 5 stars', 'Well..."
...,...,...,...,...,...,...,...,...,...,...
380,Sauna Shirt for Men – Compression Heat Trappin...,$25.10 with 11 percent savings,$28.30,3.6 out of 5 stars,(19),$64.02 Shipping & Import Charges to Pakistan,Heat trapping,Hand Wash Only,Imported,"{""I'm Getting 2 More..."": '5 out of 5 stars', ..."
381,Kewlioo Women's Heat Trapping Sauna Shirt - Sw...,$26.49,NaN,4.0 out of 5 stars,(807),$72.63 Shipping & Import Charges to Pakistan,Hand Wash Only,Imported,"MORE COVERAGE, MORE RESULTS - Made to trap bod...","{'Practico': '5 out of 5 stars', 'Grandeur méd..."
382,Evervibe 3 Pack Big and Tall Mens Sweat Shorts...,$38.99,NaN,4.5 out of 5 stars,(71),$93.13 Shipping & Import Charges to Pakistan,"85% Polyester, 10% Cotton, 5% Spandex",Knee High,Utility Pocket,"{'No complaints': '5 out of 5 stars', 'Love th..."
383,NORTHYARD Men's Athletic Running Pants Lightwe...,$28.99,NaN,4.5 out of 5 stars,"(2,537)",$76.52 Shipping & Import Charges to Pakistan,"90% Polyester, 10% Elastane",Imported,Mid Rise,"{'Perfekt.': '5 out of 5 stars', 'trägt sich g..."
384,CANGHPGIN Mens Workout Athletic Shorts 7 inch ...,$19.99,NaN,4.5 out of 5 stars,(444),$68.25 Shipping & Import Charges to Pakistan,"90% Nylon, 10% Spandex","Machine Wash, Hand Wash Only",Imported,"{'Finally, versatile and comfortable shorts th..."

## Removing Empty & Duplicate Rows and Handling Null Values

In [20]:
# Safely replace only exact '{}' in Customer Reviews, then drop empty rowsds['Customer Reviews'] = ds['Customer Reviews'].astype(str).str.strip()
mask = ds['Customer Reviews'].eq('{}')
ds.loc[mask, 'Customer Reviews'] = np.nan
# drop rows where every column is NaN
ds = ds.dropna(how='all')
ds = ds.drop_duplicates(ignore_index=True)
ds.to_csv('4-amazon_products_cleaned.csv', index=False)
ds

,Product Name,Current Price,Typical Price,Rating,Total Reviews,Delivery Charges,Fabric Type,Care Instructions,Origin,Customer Reviews
0,MAGCOMSEN Men's Short Sleeve Moisture Wicking ...,"PKR 2,782.71 with 60 percent savings","PKR6,958.18",4.1 out of 5 stars,(49),"PKR 17,796.56 Shipping & Import Charges to Pak...",100% Polyester,Imported,Pull On,"{'Hubby loves them!': '5 out of 5 stars', 'Per..."
1,Kewlioo Men's Heat Trapping Zipper Sweat Enhan...,"PKR 6,682.41",NaN,4.2 out of 5 stars,"(6,804)","PKR 17,896.84 Shipping & Import Charges to Pak...","Outer: 90% Polyester, 10% Spandex. Inner: 100%...",Machine Wash,Imported,"{'Passt die Größe': '3 out of 5 stars', 'Gym':..."
2,HOTSUIT Sauna Suit for Men Sweat Sauna Jacket ...,"PKR 11,417.76",NaN,4.6 out of 5 stars,"(9,967)","PKR 21,008.24 Shipping & Import Charges to Pak...",Polyester,Hand Wash Only,Imported,"{'Super zum Abnehmen': '5 out of 5 stars', 'Bo..."
3,INTO THE AM Mens T Shirts Soft Cotton Blend Cr...,"PKR 3,328.67",NaN,4.4 out of 5 stars,"(31,438)","PKR 20,387.07 Shipping & Import Charges to Pak...","60% Cotton, 40% Polyester",Machine Wash,Made in the USA or Imported,"{'Good': '5 out of 5 stars', 'Valor Precio': '..."
4,Kinglaman 1/5 Pack Mesh Workout Shirts for Men...,"PKR 6,682.41",NaN,4.6 out of 5 stars,"(2,810)","PKR 24,442.76 Shipping & Import Charges to Pak...",1OO% Polyester,Machine Wash,Imported,"{'Value for money!': '5 out of 5 stars', 'Well..."
...,...,...,...,...,...,...,...,...,...,...
219,Sauna Shirt for Men – Compression Heat Trappin...,$25.10 with 11 percent savings,$28.30,3.6 out of 5 stars,(19),$64.02 Shipping & Import Charges to Pakistan,Heat trapping,Hand Wash Only,Imported,"{""I'm Getting 2 More..."": '5 out of 5 stars', ..."
220,Kewlioo Women's Heat Trapping Sauna Shirt - Sw...,$26.49,NaN,4.0 out of 5 stars,(807),$72.63 Shipping & Import Charges to Pakistan,Hand Wash Only,Imported,"MORE COVERAGE, MORE RESULTS - Made to trap bod...","{'Practico': '5 out of 5 stars', 'Grandeur méd..."
221,Evervibe 3 Pack Big and Tall Mens Sweat Shorts...,$38.99,NaN,4.5 out of 5 stars,(71),$93.13 Shipping & Import Charges to Pakistan,"85% Polyester, 10% Cotton, 5% Spandex",Knee High,Utility Pocket,"{'No complaints': '5 out of 5 stars', 'Love th..."
222,NORTHYARD Men's Athletic Running Pants Lightwe...,$28.99,NaN,4.5 out of 5 stars,"(2,537)",$76.52 Shipping & Import Charges to Pakistan,"90% Polyester, 10% Elastane",Imported,Mid Rise,"{'Perfekt.': '5 out of 5 stars', 'trägt sich g..."
223,CANGHPGIN Mens Workout Athletic Shorts 7 inch ...,$19.99,NaN,4.5 out of 5 stars,(444),$68.25 Shipping & Import Charges to Pakistan,"90% Nylon, 10% Spandex","Machine Wash, Hand Wash Only",Imported,"{'Finally, versatile and comfortable shorts th..."

## Striping Numerical Values From String Columns

In [21]:
ds['Current Price'] = ds['Current Price'].str.split('with',expand=True)[0].str.replace(',','')
ds['Currency'] = ds['Current Price'].str.replace(r'([0-9]+.)','',regex=True)
ds['Current Price'] = ds['Current Price'].str.extract(r'([0-9]+\.[0-9]+)').astype(float)
ds['Typical Price'] = ds['Typical Price'].str.replace(',','').str.extract(r'([0-9]+\.[0-9]+)').astype(float)
ds['Rating'] = ds['Rating'].str.extract(r'([0-9]+\.[0-9])').astype(float)
ds['Total Reviews'] = ds['Total Reviews'].str.replace(',','').str.extract(r'([0-9]+)').astype(float)
ds['Delivery Charges'] = ds['Delivery Charges'].str.replace(',','').str.extract(r'([0-9]+)').astype(float)

## Adding Discount And Discount Percentage Columns

In [22]:
# Compute discount amount and percent
ds['Current Price'] = pd.to_numeric(ds['Current Price'], errors='coerce')
ds['Typical Price'] = pd.to_numeric(ds['Typical Price'], errors='coerce')
ds['Discount Amount'] = ds['Typical Price'] - ds['Current Price']
ds['Discount Percent'] = (ds['Discount Amount'] / ds['Typical Price'] * 100).round(2)
ds[['Product Name','Current Price','Typical Price','Discount Amount','Discount Percent']].head()

,Product Name,Current Price,Typical Price,Discount Amount,Discount Percent
0,MAGCOMSEN Men's Short Sleeve Moisture Wicking ...,2782.71,6958.18,4175.47,60.01
1,Kewlioo Men's Heat Trapping Zipper Sweat Enhan...,6682.41,NaN,NaN,NaN
2,HOTSUIT Sauna Suit for Men Sweat Sauna Jacket ...,11417.76,NaN,NaN,NaN
3,INTO THE AM Mens T Shirts Soft Cotton Blend Cr...,3328.67,NaN,NaN,NaN
4,Kinglaman 1/5 Pack Mesh Workout Shirts for Men...,6682.41,NaN,NaN,NaN

## Converting Prices Based On Currency

In [23]:
print('Total Currencies')
ds['Currency'].value_counts()

Total Currencies

Currency
PKR     139
$        63
Name: count, dtype: int64

In [24]:
exchange_rate = 280.0  # set current USD→PKR rate
mask = ds['Currency'].astype(str).str.contains(r'\$|USD|usd|US\$', na=False)
convert_cols = [c for c in ['Current Price', 'Typical Price', 'Discount Amount', 'Delivery Charges'] if c in ds.columns]
for c in convert_cols:
	ds.loc[mask, c] = pd.to_numeric(ds.loc[mask, c], errors='coerce') * exchange_rate
ds.loc[mask, 'Currency'] = 'PKR'
if convert_cols:
	ds[convert_cols] = ds[convert_cols].round(2)

## Creating DataSet

In [25]:
ds.to_csv('5-amazon_products.csv', index=False)
ds

,Product Name,Current Price,Typical Price,Rating,Total Reviews,Delivery Charges,Fabric Type,Care Instructions,Origin,Customer Reviews,Currency,Discount Amount,Discount Percent
0,MAGCOMSEN Men's Short Sleeve Moisture Wicking ...,2782.71,6958.18,4.1,49.0,17796.0,100% Polyester,Imported,Pull On,"{'Hubby loves them!': '5 out of 5 stars', 'Per...",PKR,4175.47,60.01
1,Kewlioo Men's Heat Trapping Zipper Sweat Enhan...,6682.41,NaN,4.2,6804.0,17896.0,"Outer: 90% Polyester, 10% Spandex. Inner: 100%...",Machine Wash,Imported,"{'Passt die Größe': '3 out of 5 stars', 'Gym':...",PKR,NaN,NaN
2,HOTSUIT Sauna Suit for Men Sweat Sauna Jacket ...,11417.76,NaN,4.6,9967.0,21008.0,Polyester,Hand Wash Only,Imported,"{'Super zum Abnehmen': '5 out of 5 stars', 'Bo...",PKR,NaN,NaN
3,INTO THE AM Mens T Shirts Soft Cotton Blend Cr...,3328.67,NaN,4.4,31438.0,20387.0,"60% Cotton, 40% Polyester",Machine Wash,Made in the USA or Imported,"{'Good': '5 out of 5 stars', 'Valor Precio': '...",PKR,NaN,NaN
4,Kinglaman 1/5 Pack Mesh Workout Shirts for Men...,6682.41,NaN,4.6,2810.0,24442.0,1OO% Polyester,Machine Wash,Imported,"{'Value for money!': '5 out of 5 stars', 'Well...",PKR,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,Sauna Shirt for Men – Compression Heat Trappin...,7028.00,7924.00,3.6,19.0,17920.0,Heat trapping,Hand Wash Only,Imported,"{""I'm Getting 2 More..."": '5 out of 5 stars', ...",PKR,896.00,11.31
220,Kewlioo Women's Heat Trapping Sauna Shirt - Sw...,7417.20,NaN,4.0,807.0,20160.0,Hand Wash Only,Imported,"MORE COVERAGE, MORE RESULTS - Made to trap bod...","{'Practico': '5 out of 5 stars', 'Grandeur méd...",PKR,NaN,NaN
221,Evervibe 3 Pack Big and Tall Mens Sweat Shorts...,10917.20,NaN,4.5,71.0,26040.0,"85% Polyester, 10% Cotton, 5% Spandex",Knee High,Utility Pocket,"{'No complaints': '5 out of 5 stars', 'Love th...",PKR,NaN,NaN
222,NORTHYARD Men's Athletic Running Pants Lightwe...,8117.20,NaN,4.5,2537.0,21280.0,"90% Polyester, 10% Elastane",Imported,Mid Rise,"{'Perfekt.': '5 out of 5 stars', 'trägt sich g...",PKR,NaN,NaN
223,CANGHPGIN Mens Workout Athletic Shorts 7 inch ...,5597.20,NaN,4.5,444.0,19040.0,"90% Nylon, 10% Spandex","Machine Wash, Hand Wash Only",Imported,"{'Finally, versatile and comfortable shorts th...",PKR,NaN,NaN

## Cleaned Dataset Info

In [26]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product Name       224 non-null    str
 1   Current Price      202 non-null    float64
 2   Typical Price      99 non-null     float64
 3   Rating             224 non-null    float64
 4   Total Reviews      224 non-null    float64
 5   Delivery Charges   199 non-null    float64
 6   Fabric Type        219 non-null    str
 7   Care Instructions  219 non-null    str
 8   Origin             219 non-null    str
 9   Customer Reviews   190 non-null    str
 10  Currency           202 non-null    str
 11  Discount Amount    99 non-null     float64
 12  Discount Percent   99 non-null     float64
dtypes: float64(7), str(6)
memory usage: 22.9 KB